brew "bun"
brew "node@26"
brew "deno"
brew "go"
brew "pnpm"
brew "git"
brew "lazygit"
brew "opencode"
brew "tmux"
brew "neovim"
brew "sketchybar"

brew "jq"
brew "fzf"
brew "ripgrep"
brew "tuicr"
brew "bat"
brew "eza"
brew "atuin"
brew "borders"
brew "stow"

brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-system-clipboard"

cask "aerospace"
cask "ghostty"
cask "vicinae"
cask "font-jetbrains-mono-nerd-font"
cask "font-sketchybar-app-font"
