tap "FelixKratz/formulae", trusted: true
tap "nikitabobko/tap", trusted: true

brew "git"
brew "git-delta"
brew "lazygit"
brew "opencode"
brew "tmux"
brew "workmux"
brew "neovim"
brew "sketchybar"
brew "timewarrior"
brew "tree-sitter-cli"
brew "bitwarden-cli"
brew "mise"

brew "jq"
brew "fzf"
brew "fd"
brew "ripgrep"
brew "tuicr"
brew "bat"
brew "eza"
brew "atuin"
brew "borders"
brew "stow"
brew "yazi"
brew "zoxide"

brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-system-clipboard"

cask "aerospace"
cask "ghostty"
cask "vicinae"
cask "sim-daltonism"
cask "font-jetbrains-mono-nerd-font"
cask "font-sketchybar-app-font"
